services:
    php:
        container_name: best_ever_world_php
        restart: on-failure
        build: ./php/development
        environment:
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
        volumes:
            - ./../:/var/www
            - ./php/development/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./php/development/memory_limit.ini:/usr/local/etc/php/conf.d/memory_limit.ini
        networks:
            - local_dev_network_best_ever_world
