name: Builds and Tests

on:
  push:
    branches:
    - 'main'
    - 'master'
  pull_request:
    branches:
    - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system:
          - 'ubuntu-latest'
        php-version:
          - '8.3'
        dependency:
          - 'highest'

    name: PHP version ${{ matrix.php-version }} with ${{ matrix.dependency }} dependencies tests on ${{ matrix.operating-system }}

    steps:
      - name: Setup PHP version ${{ matrix.php-version }} with ${{ matrix.dependency }} dependencies on ${{ matrix.operating-system }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug

      - name: Check PHP version
        run: php -v

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --optimize-autoloader --prefer-dist --no-progress --no-interaction

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependency }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependency }}-${{ hashFiles('**/composer.json') }}

      - name: Boot the build and cache directories
        run: composer dev:build:boot

      - name: Run the PHPStan static analyzer
        run: composer dev:analyze:phpstan

      - name: Run PHP Lint to check and detect syntax errors
        run: composer dev:syntax:lint

      - name: Run PHP Coding Standards Fixer to check and detect violations of pre-defined coding standards
        run: composer dev:syntax:phpcs

      - name: Cleans the build and cache directories
        run: composer dev:build:clean
